name: Build ImmortalWrt v24.10.2 (MX4200v1) — auto pull latest qosmio NSS

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # weekly; adjust as you like
  push:
    branches:
      - main

env:
  IMMORTAL_TAG: v24.10.2
  IMMORTAL_DIR: openwrt
  QOSMIO_REPO: https://github.com/qosmio/openwrt-ipq.git
  QOSMIO_FEED_REPO: https://github.com/qosmio/nss-packages.git
  CONFIG_FILE: mx4200v1.config
  CUSTOM_FILES_PATH: files/
  TARGET_SUBDIR: bin/targets/qualcommax/ipq807x

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 480

    steps:
      - name: Checkout builder repo (this repo)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
            gettext git java-propose-classpath libelf-dev libncurses5-dev \
            libncursesw5-dev libssl-dev python3 python3.12-distutils python3-setuptools \
            python3-pyelftools unzip wget zlib1g-dev rsync bc

      - name: Clone ImmortalWrt v${{ env.IMMORTAL_TAG }}
        run: |
          git clone --depth 1 --branch "$IMMORTAL_TAG" https://github.com/immortalwrt/immortalwrt.git "$IMMORTAL_DIR"

      - name: Clone latest qosmio OpenWrt-IPQ and nss-packages feeds
        run: |
          git clone --depth 1 "$QOSMIO_REPO" qosmio-openwrt || (echo "qosmio clone failed" && exit 1)
          git clone --depth 1 "$QOSMIO_FEED_REPO" qosmio-nss-packages || (echo "qosmio nss-packages clone failed" && exit 1)

      - name: Copy qosmio kernel patches, target & package additions
        run: |
          set -euo pipefail
          cd "$IMMORTAL_DIR"
          if [ -d ../qosmio-openwrt/target/linux ]; then
            rsync
